data_path: /Users/admin/eeg-ds004504
derivatives: false
freqBands:
  Alpha:
    - 8
    - 12
  Beta:
    - 12
    - 30
  Delta:
    - 0.5
    - 4
  Theta:
    - 4
    - 8
  custom1:
    - 9
    - 11
method: welch
stepSize: 1.5
windowLength: 3
